version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      # Mount the SQLite database file for persistence
      - ./prisma:/app/prisma
    restart: unless-stopped